name: woqu
stages: 
    - name: 构建打包
      jobs: 
        - name: compile-job-centos6.7
          tasks: 
            - name: compile-task-centos6.7
              type: oe-compile
              params: 
                osType: centos6.7
        - name: compile-job-centos7.2
          tasks: 
            - name: compile-task-centos7.2
              type: oe-compile
              params: 
                osType: centos7.2
    - name: 去odin上线
      trigger: manual
      jobs: 
        - name: deploy-job-in-odin
          tasks: 
            - name: deploy-task-in-odin
              type: oe-deploy:odin

